# Generated by Django 5.0.3 on 2024-03-14 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_role_user_rolt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rolt',
            new_name='role',
        ),
    ]
