# Generated by Django 5.0.3 on 2024-03-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
