# Generated by Django 5.0.3 on 2024-03-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
