# Generated by Django 5.0.3 on 2024-03-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_patient_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="Reasone_reject",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
