# Generated by Django 5.0.3 on 2024-03-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_appointment_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=1
            ),
        ),
    ]
