# Generated by Django 5.0.3 on 2024-03-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_doctor_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
