# Generated by Django 5.0.3 on 2024-03-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_remove_availability_available_times_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="availability_s",
            field=models.JSONField(default=dict),
        ),
    ]
