# Generated by Django 5.0.3 on 2024-03-13 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customuser_patient'),
    ]

    operations = [
    ]
