# Generated by Django 5.0.3 on 2024-03-13 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20240313_2218'),
    ]

    operations = [
    ]
