# Generated by Django 5.0.3 on 2024-03-18 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_doctor_availability_s"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="availability_s",
        ),
    ]
