# Generated by Django 5.0.3 on 2024-03-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_remove_doctor_availability_s"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="date_time",
            field=models.CharField(),
        ),
    ]
