# Generated by Django 5.0.3 on 2024-03-13 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20240313_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='doctor',
        ),
    ]
