# Generated by Django 5.0.3 on 2024-03-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_alter_appointment_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availability",
            name="day",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
