# Generated by Django 5.0.3 on 2024-03-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_availability_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_email',
            field=models.EmailField(default='ahmedredaelrmam@gmail.com', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
