# Generated by Django 5.0.2 on 2024-03-19 06:14

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expire',
            field=models.CharField(max_length=5, validators=[myapp.models.MMYYYYValidator()]),
        ),
    ]
