# Generated by Django 5.0.2 on 2024-03-19 06:15

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_payment_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expire',
            field=models.CharField(max_length=7, validators=[myapp.models.MMYYYYValidator()]),
        ),
    ]
