# Generated by Django 5.0.3 on 2024-03-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_appointment_patient_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient_email',
        ),
        migrations.AddField(
            model_name='appointment',
            name='field',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
