# Generated by Django 5.0.3 on 2024-03-20 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_appointment_patient_email_appointment_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='field',
            new_name='patient_email',
        ),
    ]
