# Generated by Django 5.0.3 on 2024-03-20 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_field_appointment_patient_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient_email',
        ),
    ]
