# Generated by Django 5.0.3 on 2024-03-20 01:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_alter_availability_day"),
        ("myapp", "0015_alter_payment_payment_date"),
    ]

    operations = []
