# Generated by Django 5.0.3 on 2024-03-20 02:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0016_merge_20240320_0126"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="status",
        ),
    ]
