# Generated by Django 5.0.3 on 2024-03-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_appointment_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='username',
            field=models.CharField(default='a', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
