# Generated by Django 5.0.3 on 2024-03-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_appointment_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
