# Generated by Django 5.0.3 on 2024-03-20 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0017_remove_appointment_status"),
        ("myapp", "0018_alter_appointment_username"),
    ]

    operations = []
