# Generated by Django 5.0.3 on 2024-03-22 21:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0015_alter_payment_payment_date"),
        ("myapp", "0018_alter_appointment_username"),
    ]

    operations = []
