# Generated by Django 5.0.3 on 2024-03-22 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0019_merge_20240322_2131"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.doctor",
            ),
        ),
    ]
