# Generated by Django 5.0.3 on 2024-03-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0019_merge_20240320_1919"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="username",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
