# Generated by Django 5.0.3 on 2024-03-22 21:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0020_payment_doctor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="doctor",
        ),
    ]
