# Generated by Django 5.0.3 on 2024-03-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0021_remove_payment_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="Paid",
            field=models.BooleanField(default=False),
        ),
    ]
