# Generated by Django 5.0.3 on 2024-03-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_appointment_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medical_history',
        ),
        migrations.AddField(
            model_name='patient',
            name='Chronic_Kidney_Disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='Diabetes_Mellitus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='Heart_Disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='Hypertension',
            field=models.BooleanField(default=False),
        ),
    ]
