# Generated by Django 5.0.2 on 2024-03-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_appointment_status_alter_appointment_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Paid',
            field=models.BooleanField(default=False),
        ),
    ]
