# Generated by Django 5.0.3 on 2024-03-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0024_patient_medical_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="appointment_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
